### ISSUE TITLE
Error message: The certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by Redyx** [Inklay/ETS2-ATS-Sync-Helper#10]
**Describe the bug**
Error message: "The certificate has expired or is not yet valid"

**To Reproduce**
1. Click on 'SYNC JOBS'
2. When trying to update any list, it displays this error.

OBS: all my friends are having the same error

**Setup information**
- The game you're playing on (either ATS or ETS2) ETS2
- The game version 1.40
- The app version 5.9.0
- The DLCs you have none
![errorsync](https://user-images.githubusercontent.com/28689265/117974695-3f68b580-b304-11eb-971a-bb60c531e2fb.png)

**Comment by Redyx** [comment]
The same error when trying to check new versions of the program:

![checkversion](https://user-images.githubusercontent.com/28689265/117975341-f7965e00-b304-11eb-99d4-1cf9f2c4d439.png)

**Comment by Inklay** [comment]
Hey ! Thanks for repporting this issue !

This happens because the HTTPS certificates of the server have expired, will be fixed today

**Comment by Dabmm** [comment]
Hello. I have the same problem here

**Comment by Inklay** [comment]
The certificate is renewed, everything works fine, I'm closing the issue

**Comment by salihozdemirci** [comment]
we got same error for all my friends "Error message: The certificate has expired or is not yet valid"
