### ISSUE TITLE
Internet Error on sync

### ISSUE THREAD

**Issue by Inklay** [Inklay/ETS2-ATS-Sync-Helper#2]
when I press "sync jobs" it writes an error "InternetOpenUrl error 0x00002EFF". Tried it yesterday and today. Nothing changed

_Originally posted by @IgorSanj in https://github.com/davidsantos-br/ETS2Sync-Helper-4/issues/61#issuecomment-683315051_

**Comment by Inklay** [comment]
I changed the server used by the app, can you download [this version](https://github.com/Inklay/ETS2-ATS-Sync-Helper/releases/tag/v5.7.0PR2) and tell me if it happens again ?

**Comment by IgorSanj** [comment]
I downloaded the new version, but the error with the synchronization of jobs remained

**Comment by IgorSanj** [comment]
the same error appears when in the "about" window press the button to check the new version

**Comment by Inklay** [comment]
can you access this page on your browser https://inklaywebapp.azurewebsites.net/SyncHelper/app/sync ?

**Comment by IgorSanj** [comment]
writes "Unknown game."

**Comment by Inklay** [comment]
Is the Window's name "ETS2&ATS Sync Helper 5.0.7 PR2" or something else ?

**Comment by IgorSanj** [comment]
Yes, Window's name "ETS2&ATS Sync Helper 5.7.0 PR2" and that's it

**Comment by IgorSanj** [comment]
some of my friends are working fine. Me and another person writes about an error

**Comment by Inklay** [comment]
Do you have some kind of antivirus software other than Windows Defender ? My guess is that the exe can't access the internet and it's certainly blocked by something on your computer

**Comment by IgorSanj** [comment]
I don't have antivirus on my computer and I turned off the firewall

**Comment by Inklay** [comment]
Ok thanks, can you tell me what OS are you on ? I'm gonna try to reproduce your issue to find out how ti fix it

**Comment by IgorSanj** [comment]
Windows 7 Home Premium SP1 x64

**Comment by IgorSanj** [comment]
My friend who has a similar error is using windows 10

**Comment by Inklay** [comment]
Ok thanks, I'm gonna work on it but I don't know how much time it will take, sorry for the inconvenience

**Comment by IgorSanj** [comment]
Good. Thank you for working on this program.

**Comment by Adrianosjrp** [comment]
Hello friend, I found this error when synchronizing American Truck Simulator, Thanks for the work.

![Sem título](https://user-images.githubusercontent.com/71603071/93716876-82450580-fb48-11ea-86ed-1558f2ef197b.png)

**Comment by Inklay** [comment]
> Hello friend, I found this error when synchronizing American Truck Simulator, Thanks for the work.
> 
> ![Sem título](https://user-images.githubusercontent.com/71603071/93716876-82450580-fb48-11ea-86ed-1558f2ef197b.png)

Hey ! Thanks for reporting this issue !

ATS compatibility isn't available right now, I'll need a copy of the game and it's DLCs to support the game and I can't afford it right now. I'll buy the game and start working on it the sooner I'll can

**Comment by cjhowen** [comment]
![image](https://user-images.githubusercontent.com/72145819/94695150-23f9fd00-0368-11eb-888a-1dcf55e08790.png)
I got this HTTP connection error. What happened? (ETS)

**Comment by Adrianosjrp** [comment]
> > Olá amigo, eu encontrei este erro ao sincronizar American Truck Simulator, obrigado pelo trabalho.
> > ![Sem título](https://user-images.githubusercontent.com/71603071/93716876-82450580-fb48-11ea-86ed-1558f2ef197b.png)
> 
> Ei! Obrigado por relatar esse problema!
> 
> A compatibilidade ats não está disponível agora, eu vou precisar de uma cópia do jogo e são DLCs para apoiar o jogo e eu não posso pagar isso agora. Eu vou comprar o jogo e começar a trabalhar nele mais cedo eu vou



> > Hello friend, I found this error when synchronizing American Truck Simulator, Thanks for the work.
> > ![Sem título](https://user-images.githubusercontent.com/71603071/93716876-82450580-fb48-11ea-86ed-1558f2ef197b.png)
> 
> Hey ! Thanks for reporting this issue !
> 
> ATS compatibility isn't available right now, I'll need a copy of the game and it's DLCs to support the game and I can't afford it right now. I'll buy the game and start working on it the sooner I'll can

thank you friend for answering me, and thank you very much for continuing this work and making ourselves happy.

> > Hello friend, I found this error when synchronizing American Truck Simulator, Thanks for the work.
> > ![Sem título](https://user-images.githubusercontent.com/71603071/93716876-82450580-fb48-11ea-86ed-1558f2ef197b.png)
> 
> Hey ! Thanks for reporting this issue !
> 
> ATS compatibility isn't available right now, I'll need a copy of the game and it's DLCs to support the game and I can't afford it right now. I'll buy the game and start working on it the sooner I'll can

thank you friend for answering me, and thank you very much for continuing this work and making ourselves happy.

**Comment by Inklay** [comment]
@IgorSanj Sorry i was kinda busy, it looks like the error you get is only from your side, the document of the network api used by the former developer says "The connection with the server has been reset." I don't know what can cause this error on your computer but there is nothing I can do in the code to fix this, maybe you have a proxy or you're using a VPN ?

**Comment by Inklay** [comment]
> ![image](https://user-images.githubusercontent.com/72145819/94695150-23f9fd00-0368-11eb-888a-1dcf55e08790.png)
> I got this HTTP connection error. What happened? (ETS)

I'm moving the server used by the app, when everything will be done I'll publish a new version that you'll have to download. It shouldn't take long

**Comment by IgorSanj** [comment]
@Inklay Hey. Thank you for taking the time to understand this issue. No, I do not use proxy or VPN. Thanks again. I will try to figure out what can block access to the site on my PC

**Comment by IgorSanj** [comment]
@Inklay Can you please provide a link to the server that the software is accessing?

**Comment by Inklay** [comment]
The server is currently in deployment, I'll send you the link when it'll be done

**Comment by Inklay** [comment]
@IgorSanj the new server is up and running at http://webservices-env.eba-nh6hq243.us-east-1.elasticbeanstalk.com/

**Comment by Inklay** [comment]
@cjhowen you can download the new version here https://github.com/Inklay/ETS2-ATS-Sync-Helper/releases/tag/v5.7.0 ;)

**Comment by IgorSanj** [comment]
@Inklay I downloaded the new version. Now there is no problem uploading the file. Everything works fine

**Comment by Inklay** [comment]
I'm glad to here that ! Have fun playing with your friend !

**Comment by Inklay** [comment]
hey @Adrianosjrp ! I released a new version with ATS support ;)
