### ISSUE TITLE
Sync helper problems 

### ISSUE THREAD

**Issue by lonewolf5801** [Inklay/ETS2-ATS-Sync-Helper#4]
A couple friends of mine are trying to use the sync helper for ATS. 1 has the problem of checking the DLC list Idaho and Utah are grayed out and not checkable even though he has both of those DLCs. The other friend also had issues the when he installs sync helper it thinks he has ETS2 because the DLC list shows for ETS2 and he does not have that game installed. Any help on this matter please. Thanks

**Comment by RusskiPotc** [comment]
Good afternoon
Unhandled unknown exception; terminationg  the thread in which it happened, such a problem what to do ?

**Comment by Inklay** [comment]
@lonewolf5801 I'll check about the dlcs for ATS. concerning you friend with the ETS DLC list showing up, he just has to change tab and go on the ATS one, it should work fine

**Comment by lonewolf5801** [comment]
That's the problem tho. Even if he puts mark in for ATS it still shows ETS2 DLC listSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Kylian Lavergne <notifications@github.com> Date: 11/10/20  9:50 AM  (GMT-05:00) To: Inklay/ETS2-ATS-Sync-Helper <ETS2-ATS-Sync-Helper@noreply.github.com> Cc: lonewolf5801 <sanner05@twc.com>, Mention <mention@noreply.github.com> Subject: Re: [Inklay/ETS2-ATS-Sync-Helper] Sync helper problems  (#4) 
@lonewolf5801 I'll check about the dlcs for ATS. concerning you friend with the ETS DLC list showing up, he just has to change tab and go on the ATS one, it should work fine

**Comment by lonewolf5801** [comment]
That's the thing. Even tho he puts dot in ats the  DLC still shows for ETS2.  My other friend Utah and Idaho are not clickable even tho he owns both Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Kylian Lavergne <notifications@github.com> Date: 11/10/20  9:50 AM  (GMT-05:00) To: Inklay/ETS2-ATS-Sync-Helper <ETS2-ATS-Sync-Helper@noreply.github.com> Cc: lonewolf5801 <sanner05@twc.com>, Mention <mention@noreply.github.com> Subject: Re: [Inklay/ETS2-ATS-Sync-Helper] Sync helper problems  (#4) 
@lonewolf5801 I'll check about the dlcs for ATS. concerning you friend with the ETS DLC list showing up, he just has to change tab and go on the ATS one, it should work fine

**Comment by lonewolf5801** [comment]
Now when trying to use sync it give error that needs to be saved as text file even tho on top it says Settings Ok in greenSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Kylian Lavergne <notifications@github.com> Date: 11/10/20  9:50 AM  (GMT-05:00) To: Inklay/ETS2-ATS-Sync-Helper <ETS2-ATS-Sync-Helper@noreply.github.com> Cc: lonewolf5801 <sanner05@twc.com>, Mention <mention@noreply.github.com> Subject: Re: [Inklay/ETS2-ATS-Sync-Helper] Sync helper problems  (#4) 
@lonewolf5801 I'll check about the dlcs for ATS. concerning you friend with the ETS DLC list showing up, he just has to change tab and go on the ATS one, it should work fine

**Comment by Inklay** [comment]
Hey sorry for the late reply I was really busy those last months. Do your friends still have issues ?
