### ISSUE TITLE
Sync doesn't work if not all DLCs are owned

### ISSUE THREAD

**Issue by KamilLenica** [Inklay/ETS2-ATS-Sync-Helper#5]
I have all DLCs and sync works

I've copied my friends profile to my machine, He doesn;t own France, Italy and Baltic DLCs

Sync doesn't work on this profile

**Comment by Inklay** [comment]
Are the the checkboxes of the DLCs your friend doesn' own are greyed out when you select his profile ?

**Comment by KamilLenica** [comment]
yes, they are

**Comment by Inklay** [comment]
Ok thanks I'll check it out ;)

**Comment by Inklay** [comment]
when your friend does the sync, does the game says something like "changes have been detected in the game" when he loads the save ?

**Comment by KamilLenica** [comment]
Yes it does, but jobs are not synced.

Also tried clearing jobs - this works
reset economy - works aswell

**Comment by Inklay** [comment]
Ok I see, i guess the 1.39 broke some job lists, I'll have a look on that and I'll fix it this week ;)

**Comment by KamilLenica** [comment]
I don't know how jobs are generated, i have game reverted back to 2.38

**Comment by jkvint** [comment]
fix it?

**Comment by Inklay** [comment]
I just found out that I totally forget to reply on this issue my bad....
I added 1.39 compatibility for ETS2 on a server side update so you don't have to download anything. Do you still have any issue with the DLC ?
