### ISSUE TITLE
Sync doesn't work on 1.39

### ISSUE THREAD

**Issue by KamilLenica** [Inklay/ETS2-ATS-Sync-Helper#6]
Using 5.8.0 cannot sync jobs on ETS 1.39

**Comment by jkvint** [comment]
+1

**Comment by akifunal** [comment]
+1+1

**Comment by marcelog09** [comment]
+1+1

**Comment by Inklay** [comment]
Sorry for the late reply, I'm starting to work on it, I'll keep you in touch

**Comment by KamilLenica** [comment]
no problem, it's pro bono after all

**Comment by Inklay** [comment]
The issue seems pretty easy to fix, if everything work as I think, it should be fixed this week

**Comment by Inklay** [comment]
The fix is online for ETS2 and you don't need to download another version of the client, everything was done server side. the fix for ATS will be done pretty soon too and will add Colorado as well.
Thank you for patience !
