### ISSUE TITLE
Unhandled unknown exception

### ISSUE THREAD

**Issue by IgorSanj** [Inklay/ETS2-ATS-Sync-Helper#7]
When trying to synchronize jobs, the program gives this error:
![image](https://user-images.githubusercontent.com/70383381/113384044-e107f900-938d-11eb-82fa-5fa24b8f4334.png)

**Setup information**
- The game you're playing on  ETS2
- The game version 1.39.4.5s
- The app version 5.8.2
- The DLCs I have Heavy Cargo Pack, Scandinavia, Going East!, High Power Cargo Pack 
- Windows 7 x64 SP1

**Comment by Inklay** [comment]
Thanks for reporting this issue, I'm gonna try to reproduce this error, I'll keep you updated !

**Comment by Inklay** [comment]
Hey ! Can you hand me the ETS2 profile you're using with the SyncHelper ?

**Comment by IgorSanj** [comment]
Hello, sorry for the delay. Here is the folder with the game profile
[profiles.zip](https://github.com/Inklay/ETS2-ATS-Sync-Helper/files/6312809/profiles.zip)

**Comment by Inklay** [comment]
Thanks ! I'm gonna try with your profile in the next  few days

**Comment by Mxrynd** [comment]
@IgorSanj try to add sync helper to ativirus white list

**Comment by IgorSanj** [comment]
Many thanks. That helped. Somehow I didn't even think that there might be a problem in it
